#!/bin/bash
# Author Mister Mjir
# ------------------
# Made for use with clang++, although might also work with clang, g, and g++ maybe?
# Just call this script and give a name for the executable that will be produced
# This is my first shell script so there may be some major issues, but nothing destructive (hopefully)
# Don't make the directories have weird names, apparently parsing ls data is bad but I am doing it

i=0
while read line
do
  DIRECTORIES[$i]="$line"
  ((i++))
done < <(find . -type d)
DIRECTORIES=( "${DIRECTORIES[@]/.\/}") # Better format

if [ ${#DIRECTORIES[@]} -gt 1 ]
then
  for (( i=1; i<${#DIRECTORIES[@]}; i++));
  do
    SOURCE[i]="${DIRECTORIES[i]}/*.cpp"
    DIRECTORIES[i]="-I./${DIRECTORIES[i]}"
  done
  clang++ *.cpp ${SOURCE[@]} -o $1 ${DIRECTORIES[@]:1:${#DIRECTORIES[@]}}
else
  clang++ *.cpp -o $1
fi
