#!/bin/bash
# Author Mister Mjir
# ------------------
# Compile any C project with clang, clang++, g, or g++
# Just call this script and give the compiler and the name of the output file
# This is my first shell script so there may be some major issues, but nothing destructive (hopefully)
# Don't make the directories have weird names, apparently parsing ls data is bad but I am doing it

i=0
while read line
do
  DIRECTORIES[$i]="$line"
  ((i++))
done < <(find . -type d)
DIRECTORIES=( "${DIRECTORIES[@]/.\/}") # Better format

if [ ${#DIRECTORIES[@]} -gt 1 ]
then
  for (( i=1; i<${#DIRECTORIES[@]}; i++));
  do
    SOURCE[i]="${DIRECTORIES[i]}/*.cpp"
    DIRECTORIES[i]="-I./${DIRECTORIES[i]}"
  done
  $1 *.cpp ${SOURCE[@]} -o $2 ${DIRECTORIES[@]:1:${#DIRECTORIES[@]}} ${@:3}
else
  $1 *.cpp -o $2 ${@:3}
fi
